"""
Question Validator Module - Validates generated questions.

This module provides validation functions for questions.
It does NOT generate or modify questions.
"""

import re
from typing import Dict, Any, List
from difflib import SequenceMatcher

from .options_parser import (
    get_correct_text_from_options,
    extract_option_text,
    extract_option_letter,
)

from .validation_logger import log_validation_failure

from .question_constants import MAX_QUESTION_LENGTH

from ..models.question_schema import validate_question_schema

# ==========================================
# CONSTANTS
# ==========================================

# Common words to ignore in concept matching
STOP_WORDS = {
    'the', 'this', 'that', 'these', 'those', 'a', 'an',
    'of', 'for', 'with', 'without', 'from', 'to', 'by',
    'on', 'at', 'in', 'into', 'through', 'during'
}

# Invalid single-word concepts (verbs, adjectives, generic terms)
INVALID_CONCEPT_WORDS = {
    'allows', 'provides', 'enables', 'stores', 'manages', 'reduces', 'improves',
    'uses', 'supports', 'offers', 'helps', 'contains', 'includes', 'does', 'doing',
    'responsible', 'processing', 'maintaining', 'organizing', 'allow', 'provide',
    'enable', 'store', 'manage', 'reduce', 'improve', 'use', 'support', 'offer',
    'help', 'contain', 'include', 'do', 'concept', 'example', 'method', 'approach',
    'technique', 'process', 'system', 'layer', 'type', 'category', 'classification',
    'service', 'platform', 'solution', 'resource', 'infrastructure', 'component',
    'module', 'thing', 'item', 'element', 'part', 'way', 'means', 'mechanism'
}

# ==========================================
# CACHE VALIDATION
# ==========================================


def is_valid_question(question: Dict[str, Any]) -> bool:
    """
    Validate a question for caching and usage.
    """

    if not question or not isinstance(question, dict):
        return False

    if not validate_question_schema(question):
        return False

    required_grounding = ["correct_text", "supporting_fact", "source_note", "fact_id"]

    for field in required_grounding:
        if field not in question or not question[field]:
            return False

    supporting_fact = str(question.get("supporting_fact", ""))

    if not supporting_fact:
        return False

    if len(supporting_fact.split()) < 3:
        return False

    invalid_markers = ["#", "[[", "]]", "---", "http", "https"]

    for marker in invalid_markers:
        if marker in supporting_fact:
            return False

    explanation = question.get("explanation", "")

    if not explanation or len(explanation.split()) < 2:
        return False

    correct_letter = question.get("correct", "")
    options = question.get("options", [])

    correct_text = get_correct_text_from_options(options, correct_letter)

    if not correct_text:
        return False

    for opt in options:
        if not opt or not extract_option_text(opt):
            return False

    return True


def has_grounded_explanation(question: Dict[str, Any]) -> bool:
    """
    Check if explanation is grounded in supporting fact.
    """

    explanation = question.get("explanation", "").lower()
    supporting_fact = question.get("supporting_fact", "").lower()
    correct_text = question.get("correct_text", "").lower()

    if not explanation or not supporting_fact or not correct_text:
        return False

    if correct_text in explanation:
        return True

    fact_words = set(supporting_fact.split())
    explanation_words = set(explanation.split())

    overlap = fact_words & explanation_words

    return len(overlap) >= 2


# ==========================================
# STRUCTURE VALIDATION
# ==========================================

def validate_distractors(question: dict) -> bool:
    """
    Reject placeholder distractors generated by LLM.
    """

    bad_patterns = [
        "distractor option",
        "option 1",
        "option 2",
        "option 3"
    ]

    for option in question.get("options", []):

        text = extract_option_text(option).lower()

        for bad in bad_patterns:
            if bad in text:
                log_validation_failure(
                    question,
                    "distractor",
                    f"Placeholder distractor detected: {text}"
                )
                return False

    return True


def validate_structure(question: dict) -> bool:

    is_fill_blank = "options" not in question

    if is_fill_blank:
        required = ["question", "correct", "explanation"]
    else:
        required = ["question", "options", "correct", "explanation"]

    missing = [field for field in required if field not in question]

    if missing:
        log_validation_failure(
            question, "structure", f"Missing required fields: {missing}"
        )
        return False

    if not is_fill_blank:
        if not isinstance(question["options"], list) or len(question["options"]) != 4:
            log_validation_failure(
                question, "structure", "Options must contain exactly 4 items"
            )
            return False

    q_text = question["question"].strip()

    # Auto-fix missing question mark from the LLM
    if q_text and not q_text.endswith("?"):
        q_text = q_text.rstrip(".!,:;") + "?"
        question["question"] = q_text

    # Validate after auto-fix
    if not q_text.endswith("?"):
        log_validation_failure(
            question,
            "structure",
            "Question does not end with '?'"
        )
        return False

    if len(q_text) > MAX_QUESTION_LENGTH:
        log_validation_failure(question, "structure", "Question exceeds maximum length")
        return False

    if re.search(r"\b[A-D]\)", q_text):
        log_validation_failure(
            question, "structure", "Question contains leaked option markers"
        )
        return False

    return True


# ==========================================
# CORRECT ANSWER VALIDATION
# ==========================================


def normalize_and_validate_correct_field(question: dict) -> bool:

    correct = str(question.get("correct", "")).strip()

    options = question.get("options", [])

    if len(options) != 4:
        return False

    if correct in ["A", "B", "C", "D"]:
        return True

    match = re.match(r"^([A-D])[\)\.\-\s]", correct)

    if match:
        question["correct"] = match.group(1)
        return True

    for option in options:

        option_letter = extract_option_letter(option)
        option_text = extract_option_text(option)

        if option_text.lower() == correct.lower():
            question["correct"] = option_letter
            return True

    log_validation_failure(
        question, "correct_field", "Unable to resolve correct answer"
    )

    return False


# ==========================================
# QUESTION FOCUS VALIDATION
# ==========================================


def _normalize_text(text: str) -> str:
    """
    Normalize text for comparison: lowercase, remove punctuation, collapse spaces.
    """
    text = text.lower()
    text = re.sub(r'[^\w\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def _extract_meaningful_words(text: str) -> List[str]:
    """
    Extract meaningful words from text (exclude stop words and short words).
    """
    words = _normalize_text(text).split()
    return [w for w in words if len(w) > 2 and w not in STOP_WORDS]


def validate_question_focus(
    question: dict,
    concept: str,
    supporting_fact: str = ""
) -> bool:
    """
    Validate that the generated question focuses on the correct concept.
    Uses flexible matching: normalized text comparison, meaningful word overlap.
    """
    q_text = question.get("question", "")
    concept_lower = concept.lower()

    # Rule 1: If question uses "layer" but concept doesn't, reject
    if "layer" in q_text.lower() and "layer" not in concept_lower:
        log_validation_failure(
            question, "focus", f"Question uses 'layer' but concept is '{concept}'"
        )
        return False

    # Normalize both texts
    q_normalized = _normalize_text(q_text)
    concept_normalized = _normalize_text(concept)

    # Rule 2:
    # Exact concept appears in the question.
    if concept_normalized in q_normalized:
        return True

    compact_question = q_normalized.replace(" ", "")
    compact_concept = concept_normalized.replace(" ", "")

    if compact_concept in compact_question:
        return True


    # Rule 3:
    # Accept questions that strongly match the supporting fact,
    # even if the concept name itself is not mentioned.

    if supporting_fact:

        fact_words = set(_extract_meaningful_words(supporting_fact))
        q_words = set(_extract_meaningful_words(q_text))

        if fact_words:

            overlap = len(fact_words & q_words) / len(fact_words)

            # Strong semantic overlap
            if overlap >= 0.35:
                return True

            # Absolute overlap for long facts
            if len(fact_words & q_words) >= 5:
                return True


    # Rule 4:
    # Fall back to concept-word matching.
    concept_words = set(_extract_meaningful_words(concept))
    q_words = set(_extract_meaningful_words(q_text))

    if concept_words:

        overlap = len(concept_words & q_words) / len(concept_words)

        if overlap >= 0.5:
            return True

        matched = sum(1 for w in concept_words if w in q_words)

        if matched:
            print(
                f"⚠️ Partial concept match for '{concept}': "
                f"{matched}/{len(concept_words)}"
            )


    # Rule 5:
    # Stem-like matching ("storage" vs "store")
    for concept_word in concept_words:
        for q_word in q_words:
            if (
                concept_word.startswith(q_word)
                or q_word.startswith(concept_word)
            ):
                return True

    log_validation_failure(
        question, "focus", f"Question doesn't reference concept '{concept}'"
    )
    return False


# ==========================================
# TOPIC RELEVANCE
# ==========================================


def is_relevant_to_topic(
    question: str, topic: str, answer: str = "", supporting_fact: str = ""
) -> bool:

    combined = " ".join([question or "", answer or "", supporting_fact or ""]).lower()

    if supporting_fact:

        words = [
            w.lower() for w in re.findall(r"[A-Za-z][A-Za-z0-9\-]{3,}", supporting_fact)
        ]

        overlap = sum(1 for word in set(words) if word in combined)

        if overlap >= 2:
            return True

    if answer:

        words = [w.lower() for w in re.findall(r"[A-Za-z][A-Za-z0-9\-]{2,}", answer)]

        if any(word in combined for word in words):
            return True

    topic_lower = topic.lower()

    if topic_lower in combined:
        return True

    for word in topic_lower.split():

        if len(word) > 3 and word in combined:
            return True

    log_validation_failure(None, "topic_relevance", "Question not related to topic")

    return False


# ==========================================
# DUPLICATE DETECTION
# ==========================================


def _normalize_question_text(text: str) -> str:
    """
    Normalize question text for duplicate detection.
    Removes punctuation, extra whitespace, and common filler phrases.
    """
    text = text.lower().strip()
    # Remove punctuation (keep letters, numbers, spaces)
    text = re.sub(r'[^\w\s]', ' ', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    # Remove common filler phrases
    filler_phrases = ['what is', 'which of the following', 'which one', 'the question']
    for phrase in filler_phrases:
        if text.startswith(phrase):
            text = text[len(phrase):].strip()
    return text


def is_duplicate_question(
    new_question: str, existing_questions: List[str], threshold: float = 0.85
) -> bool:
    """
    Check if a question is a duplicate of existing questions.
    Uses SequenceMatcher after normalizing both texts.
    """
    if not new_question or not existing_questions:
        return False

    new_normalized = _normalize_question_text(new_question)

    for old_question in existing_questions:
        if not old_question:
            continue

        old_normalized = _normalize_question_text(old_question)

        # If the normalized text is empty, skip
        if not new_normalized or not old_normalized:
            continue

        similarity = SequenceMatcher(None, new_normalized, old_normalized).ratio()

        if similarity >= threshold:
            print(f"⚠️ Duplicate question detected (similarity: {similarity:.2f})")
            return True

    return False


# ==========================================
# CONCEPT VALIDATION
# ==========================================


def is_valid_concept(concept: str) -> bool:
    """
    Check if a concept is valid for fallback generation.
    Rejects: verbs, adjectives, generic single words, vague categories.
    Accepts: technical nouns, multi-word concepts, acronyms.
    """
    if not concept:
        return False

    concept_clean = concept.strip()
    if not concept_clean:
        return False

    concept_lower = concept_clean.lower()
    words = concept_lower.split()

    # Reject: Single generic word
    if len(words) == 1:
        # Allow common acronyms (2+ uppercase letters)
        if concept_clean.isupper() and len(concept_clean) >= 2:
            return True

        # Reject: verbs, adjectives, generic terms
        if concept_lower in INVALID_CONCEPT_WORDS:
            return False

        # Reject: short words that are likely generic
        if len(concept_lower) < 4:
            return False

    # Reject: concepts that are obviously generic phrases
    generic_phrases = [
        'allows for', 'provides a', 'enables the', 'uses a', 'supports the',
        'method of', 'process of', 'system for', 'type of', 'category of'
    ]

    for phrase in generic_phrases:
        if phrase in concept_lower:
            return False

    # Reject: concepts that start with verbs
    verb_start_patterns = [
        r'^allows?\s+', r'^provides?\s+', r'^enables?\s+',
        r'^stores?\s+', r'^manages?\s+', r'^reduces?\s+',
        r'^improves?\s+', r'^uses?\s+', r'^supports?\s+',
        r'^offers?\s+', r'^helps?\s+', r'^contains?\s+',
        r'^includes?\s+', r'^does?\s+', r'^focuses?\s+'
    ]

    for pattern in verb_start_patterns:
        if re.match(pattern, concept_lower):
            return False

    # Accept: multi-word concepts (2+ words)
    if len(words) >= 2:
        # But reject if they end with generic terms
        generic_endings = ['concept', 'example', 'method', 'approach', 'technique',
                           'process', 'system', 'layer', 'type', 'category',
                           'classification', 'service', 'platform', 'solution',
                           'resource', 'infrastructure', 'component', 'module']

        if words[-1] in generic_endings:
            # Allow if it's a known concept like "Operating System"
            if len(words) >= 3:
                return True
            # Reject "Storage System" but allow "Distributed Storage System"
            if len(words) == 2:
                return words[0] not in ['abstract', 'generic', 'basic', 'simple']

    # Accept: all other multi-word concepts
    if len(words) >= 2:
        return True

    # Accept: single word that is capitalized (likely a proper noun)
    if concept_clean[0].isupper() and len(concept_clean) > 2:
        return True

    # Default: accept if it passes all checks
    return True


from .options_parser import get_correct_text_from_options


def validate_question_uniqueness(question: dict) -> bool:
    """
    Reject questions where a distractor is described by the question.
    """

    question_text = question.get("question", "").lower()

    question_type = question.get("type", "mcq")

    if question_type == "fill_blank":
        return validate_fill_blank_question(question)

    options = question.get("options", [])
    correct_letter = question.get("correct", "")

    correct = get_correct_text_from_options(options, correct_letter).lower()

    if not correct:
        return False

    question_words = set(_extract_meaningful_words(question_text))

    for option in options:
        if isinstance(option, dict):
            option_text = option.get("text", "").lower()
        else:
            option_text = str(option).lower()

        if option_text == correct:
            continue

        option_words = set(_extract_meaningful_words(option_text))

        # Exact mention
        # Ignore generic category phrases that can appear naturally
        # Example: "cloud storage technology" when answer is "Block Storage"

        generic_terms = {
            "cloud storage",
            "cloud computing",
            "data storage",
            "database",
            "technology",
            "system",
        }

        if option_text in question_text:

            if option_text not in generic_terms:
                log_validation_failure(
                    question,
                    "ambiguity",
                    f"Question mentions distractor '{option_text}'",
                )
                return False

        # Word overlap
        if option_words:

            overlap = len(question_words & option_words) / len(option_words)

            if overlap >= 0.8:
                log_validation_failure(
                    question,
                    "ambiguity",
                    f"Question could also describe '{option_text}'",
                )
                return False

        # Semantic clue detection using supporting fact
        supporting_fact = question.get("supporting_fact", "").lower()

        if supporting_fact:

            fact_words = set(_extract_meaningful_words(supporting_fact))

            option_similarity = len(
                fact_words & option_words
            ) / max(len(option_words), 1)

            question_similarity = len(
                question_words & fact_words
            ) / max(len(fact_words), 1)

            # Question follows distractor definition more than answer
            if option_similarity >= 0.5 and question_similarity >= 0.35:

                log_validation_failure(
                    question,
                    "ambiguity",
                    f"Question wording overlaps distractor concept '{option_text}'",
                )
                return False

    return True

def validate_fill_blank_question(question: dict) -> bool:
    """
    Validate fill blank questions.
    """

    text = question.get("question", "")
    correct = question.get("correct", "").strip()

    if not text:
        return False

    if not correct:
        return False

    # Must contain exactly one blank
    if text.count("_______") != 1:
        log_validation_failure(
            question,
            "fill_blank",
            "Fill blank must contain exactly one blank"
        )
        return False

    # Answer should not appear in question
    if correct.lower() in text.lower():
        log_validation_failure(
            question,
            "fill_blank",
            "Answer appears inside question"
        )
        return False

    # Reject weak generated patterns
    banned_patterns = [
        "what term describes",
        "known as",
        "what is this",
        "identify the",
        "which term"
    ]

    lower = text.lower()

    for pattern in banned_patterns:
        if pattern in lower:
            log_validation_failure(
                question,
                "fill_blank",
                f"Contains banned pattern: {pattern}"
            )
            return False

    return True